### ISSUE TITLE
Is it possible to run all of the form.io projects in docker...?

### ISSUE THREAD

**Issue by CodisRedding** [formio/help.form.io#38]
Is it possible to run all of the form.io projects on github in docker? If so, what do we lose by creating the docker containers ourselves opposed to hosting in the cloud, or even purchasing the Docker model plan?

**Comment by zackurben** [comment]
Technically yes, you can put basically anything in a docker container, but the hosted version you see is not the open source version, so you wont have nearly the same capabilities; Our hosted version is the open source+more.
