### ISSUE TITLE
Field validations in a datagrid - wizard mode - errored fields not highlighted.

### ISSUE THREAD

**Issue by tiwana007** [formio/help.form.io#49]
![data grid - validation error issue](https://user-images.githubusercontent.com/33194378/33321887-ff27fc18-d492-11e7-8ee2-a3f8c73d619b.PNG)
![data grid - validation error issue](https://user-images.githubusercontent.com/33194378/33322073-accee890-d493-11e7-8253-36ba7b3001a6.PNG)

The fields within a data grid do not get highlighted when a infield validation error occurs. A error message gets displayed on top of the page "Please fix the following errors before proceeding". This is true only when the form is in wizard mode. The errored fields are highlighted and associated error messages displayed when the form is not in wizard mode. So while in wizard mode, the validations are getting executed but there is no way to determine which field errored.

**Comment by randallknutson** [comment]
This repo is for our help documentation. Please post this in ngFormio library repository so we can look into it. This may have been fixed in the meantime.

https://github.com/formio/ngFormio
