### ISSUE TITLE
[BUG] Documentation on button element is out of date

### ISSUE THREAD

**Issue by tnorthcutt** [formio/help.form.io#93]
Currently, the [documentation on buttons states](https://github.com/formio/help.form.io/blob/6f916130e98b975cf9e00a77b8be9c4cec604bb9/_paragraphs/userguide/form-components/button.md) "Currently there are two actions that can be performed, submit and reset"

However, button components actually have seven available actions:

![CleanShot 2020-02-26 at 12 54 37@2x](https://user-images.githubusercontent.com/796639/75382368-9ae18b80-5897-11ea-8131-07568a4e650e.png)

Is there documentation somewhere on how to utilize the other actions?

**Comment by murrayw24** [comment]
It would be great to have some extra documentation around this.
