### ISSUE TITLE
Versioning - Increment vid on change of something other than components?

### ISSUE THREAD

**Issue by sorabh2008** [formio/help.form.io#94]
Hi

I am wondering if we can increment vid under form revisions on change of something other than components as well.

Use Case:
We are using formio enterprise.
We have "properties" key in the form definition.
We make any change in "property" object.

We want to increment the revision for this change.

**Comment by randallknutson** [comment]
Currently vid only changes when the components are changed as you have noticed. I think we would be open to incrementing for other changes as well. Can you provide what the use case is so we can evaluate whether to make the change or not?

**Comment by sorabh2008** [comment]
Not a problem. We have achieved this by inserting/deleting an empty custom component.
No need to make a change as it doesn't make sense to increment vid unless the definition has changed.
